In [ ]:
#array in python
import array
arr= array.array('i',[1,2,3,4,5,6,7])
print(arr)




In [ ]:
arr = array.array('i',[1 for x in range (7) ])
print(arr)

In [ ]:
from array import *
array1 = array('i',[10,20,30,40,50])
for x in array1:
    print(x)

In [ ]:

import array as arr
array1 = arr.array('d',[])
for x in range(10):
    array1.append(x)
for x in array1:
    print(x)

In [ ]:
#append and insert
import array
arr = array.array('i',[1,2,3])
print(arr)
arr.append(4)
print(arr)
arr.insert(2,5)
print(arr)

In [ ]:
#pop(),remove()
import array
arr = array.array('i',[1,2,3,4,1,12,34])
print(arr)
print("the popped element is :",end=" ")
print(arr.pop(2))#pop will take index
print(arr)
arr.remove(1)
print(arr)

In [ ]:
#reverse()
import array
arr = array.array('i',[1,2,3,4,1,2])
arr.reverse()
print("the array after reversing is ")
for i in range(0,6):
    print(arr[i],end=" ")

In [ ]:
#Matrix
#python does not hav built-in type of matrices,However we can treat list of a list as a matrix.
A=[1,2,3],[4,5,6]
#printing the matrix
for i in range(2):
    for j in range(3):
        print(A[i][j],end=" ")
        
    print()

In [ ]:
#create a dyanamic matrix using for loop
n=3
m=4
a=[0]*n
for i in range(n):
    a[i]=[0]*m
print(a)

In [ ]:
#create an 8 * 5 matrix of 0's
w,h=8,5;

MyMatrix = [ [0 for x in range( w )] for y in range ( h )]

for i in range(5):
    print(MyMatrix[i])

In [ ]:
#input data into a matrix having different row and columns and print it
print("Enter the row and column")
r = int(input("enter the number of rows in a matrix"))
c= int(input("enter the number of columns in a matrix"))
a =[[int(input())for x in range(c)]for y in range(r)]
for i in range(r):
    for j in range(c):
        print(a[i][j],end=" ")
    print()

 #using numpy create an array
 import numpy as np
 arrr = np.array([1,2,3,4,5])
 print(arr)

In [ ]:
#using numpy create an array 
import numpy as np 
arr = np.array([1,2,3,4,5])
print(arr)

In [ ]:
#array sort using numpy
import numpy as np
arr = np.array([3,4,1,2,0])
print(np.sort(arr))

In [ ]:
#sort array in descending order(flip())
import numpy as np
arr = np.array([3,4,1,2,0])
arr =np.flip(np.sort(arr))
print(arr)

In [ ]:
#array join using numpy
import numpy as np
arr1= np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
print(arr)

In [ ]:
#linear space linspace(start,stop,n) using numpy
np.linspace(0,2,20)
np.linspace(0,1,20)

In [ ]:
#matrix of zeros and ones
import numpy as np
zeros_array = np.zeros((2,3),dtype=np.int32)
print(zeros_array)

ones_array = np.ones((2,3),dtype=np.int32)
print(ones_array)

In [4]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
#generating list
list_1 = [1,2,3,4]
list_2=[5,6,7,8]
list_3 = [9,10,11,12]

#creating numpy array
sample_array = np.array([list_1,list_2,list_3])
print("numpy array is ")
print(sample_array)

In [6]:
import numpy as np
a = np.arange(15)
print(a)

b = a.reshape(3,5)
print(b)


a = np.arange(15).reshape(3,5)
print("the new array is as follows:")
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
the new array is as follows:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [9]:
#Q) create an array with starting value 20 and total values.reshape it with all possible shapes.
import numpy as np
a = np.arange(20,40).reshape(1,20)
a = np.arange(20,40).reshape(2,10)
a = np.arange(20,40).reshape(4,5)

print(a)

[[20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]


In [17]:
import numpy as np
a = np.arange(24)
print(a)
print()
print("size of the array",a.size)
print("shape of the array: ",a.shape)
print("the above array is {0} dimensional".format(a.ndim))
print("\n")

#now reshape it
x = a.reshape(4,6)
print(a)
print()
print("size of the array",x.size)
print("shape of the array: ",x.shape)
print("the above array is {0} dimensional".format(x.ndim))
print("\n")

y = a.reshape(2,4,3)
print(a)
print()
print("size of the array",y.size)
print("shape of the array: ",y.shape)
print("the above array is {0} dimensional".format(y.ndim))
print("\n")


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

size of the array 24
shape of the array:  (24,)
the above array is 1 dimensional


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

size of the array 24
shape of the array:  (4, 6)
the above array is 2 dimensional


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

size of the array 24
shape of the array:  (2, 4, 3)
the above array is 3 dimensional




In [19]:
import numpy
#two array are initialized by value
x = numpy.array([[1,2],[4,5]])
y = numpy.array([[7,8],[9,10]])
print(numpy.add(x,y))
print(numpy.subtract(x,y))
print(numpy.divide(x,y))
print(numpy.multiply(x,y))
print("the product of two matieces : ")
print(numpy.dot(x,y))

[[ 8 10]
 [13 15]]
[[-6 -6]
 [-5 -5]]
[[0.14285714 0.25      ]
 [0.44444444 0.5       ]]
[[ 7 16]
 [36 50]]
the product of two matieces : 
[[25 28]
 [73 82]]


In [21]:
#numpy.transpose()
import numpy as np
mat = np.matrix('[4,1,9;12,4,1;4,5,6]')
mat1 = mat.transpose();
#we can also use mat1 = mat.T
print(mat)
print(mat1)

[[ 4  1  9]
 [12  4  1]
 [ 4  5  6]]
[[ 4 12  4]
 [ 1  4  5]
 [ 9  1  6]]
